# nixpacks.toml

# Definimos una fase de construcción para todos los servicios
[phases.build]
# Le decimos a Nixpacks que use los comandos por defecto ("...") 
# Y LUEGO AÑADA los nuestros al final
cmds = [
  "...",
  "npm run build",
  "php artisan optimize"
]

# Definimos variables que aplican a la imagen final
[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public"